version: '3.9'

services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  face-recognition:
    build:
      context: ./face-recognition
      dockerfile: Dockerfile
    container_name: face_recognition_service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - database
    networks:
      - app-network

  identity-verification:
    build:
      context: ./identity-verification
      dockerfile: Dockerfile
    container_name: identity_verification_service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - FACE_RECOGNITION_URL=http://face-recognition:5001
    depends_on:
      - database
      - face-recognition
    networks:
      - app-network

  alert-service:
    build:
      context: ./alert-service
      dockerfile: Dockerfile
    container_name: alert_service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - identity-verification
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
